### ISSUE TITLE
Web build broken on main: Options dialog calls config_dir / plot_styles_dir unconditionally

### ISSUE THREAD

**Issue by tallbiscuits** [HakanSeven12/H7CAD#1224]
`cargo check --target wasm32-unknown-unknown` fails on `main` (verified at `12c1c330f`, and earlier at `c2d22e580`, both with a clean tree):

```
error[E0425]: cannot find function `config_dir` in module `crate::config`
   --> src/app/view/modal.rs:253:52
error[E0425]: cannot find function `plot_styles_dir` in module `crate::io::plot_style`
   --> src/app/view/modal.rs:255:65
error[E0425]: cannot find function `config_dir` in module `crate::config`
   --> src/app/view/modal.rs:260:54
error: could not compile `OpenCADStudio` (lib) due to 3 previous errors
```

### Cause

`crate::config::config_dir` and `crate::io::plot_style::plot_styles_dir` are both `#[cfg(not(target_arch = "wasm32"))]`, but the Options dialog builds its `Folders` block unconditionally.

That block was introduced by 7ea1aef95 ("Add a Files page, and links out to the editors that own their own dialogs", 2026-09-10), so this is a recent regression rather than a long-standing gap.

### Why CI hasn't caught it

`pages.yml` is the only workflow that touches wasm, and it runs on `release: published` / `workflow_call` / `workflow_dispatch` — not on pushes to `main`. The live web build therefore still comes from the last release, which predates the regression. The next weekly release would be the first to hit it.

### Suggested fix

Giving the two functions wasm bodies is smaller than gating the call site, and keeps the `cfg` in the modules that own the platform knowledge rather than spreading it into the UI — the same pairing `plot_style.rs` already uses around `builtin` / `plot_styles_dir`:

```rust
// src/config.rs
#[cfg(target_arch = "wasm32")]
pub fn config_dir() -> Option<std::path::PathBuf> {
    None
}

// src/io/plot_style.rs
#[cfg(target_arch = "wasm32")]
pub fn plot_styles_dir() -> Result<std::path::PathBuf, String> {
    Err("Plot styles folder could not be resolved".to_string())
}
```

The web has no per-user config directory — settings live in browser storage and the plot-style tables are the built-in ones — so "no path" is the honest answer and the dialog simply shows none.

I have this locally as a 15-line patch; `cargo check --target wasm32-unknown-unknown` and `cargo check` are both clean with it. Happy to open a PR if useful, or leave it to you.

### Possible follow-up

Adding `cargo check --target wasm32-unknown-unknown` to a workflow that runs on `main` would catch this class of regression before a release rather than during one.
